  services:
    web:
      build:
        context: .
        dockerfile: ./app/Dockerfile
      container_name: django_web
      command: gunicorn --workers 3 --bind 0.0.0.0:8000 core.wsgi:application

      volumes:
        - ./app:/app
      ports:
        - "8000:8000"
      environment:
        - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
        - DEBUG=${DEBUG}
        - ALLOWED_HOSTS=${ALLOWED_HOSTS}
        - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
        - FRONTEND_URL=${FRONTEND_URL}
        - PARENT_HOST=${PARENT_HOST}
        - EMAIL_HOST_USER=${EMAIL_HOST_USER}
        - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}

    nginx:
      image: nginx:latest
      container_name: nginx_proxy
      ports:
        - "80:80"   # Porta HTTP
        - "443:443" # Porta HTTPS
      environment:
        - DOMAIN_NAME=${CSRF_TRUSTED_ORIGINS}
      volumes:
        - ./nginx/site.conf.template:/etc/nginx/templates/site.conf.template
        - ./nginx/certs:/etc/nginx/certs
        - ./app/staticfiles:/staticfiles
        - ./app/media:/mediafiles
      depends_on:
        - web
