# Generated by Django 5.1.2 on 2024-10-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_project_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default=0, max_length=400),
            preserve_default=False,
        ),
    ]
