# Generated by Django 5.1.2 on 2024-10-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_remove_project_tags_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='file_type',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
