# Generated by Django 5.1.2 on 2024-10-26 22:33

import portfolios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0008_project_votes_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(upload_to=portfolios.models.user_directory_path),
        ),
    ]
