name: Django CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: PRODUCTION

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Add server to known_hosts
        run: |
          ssh-keyscan -p ${{ vars.PORT }} ${{ vars.HOST }} >> ~/.ssh/known_hosts


      - name: Copy files to server
        run: |
          rsync -avz --exclude '.git/' --exclude '.github/' -e "ssh -p ${{ vars.PORT }}" . ${{ vars.USER }}@${{ vars.HOST }}:/Portfolizer
      - name: Build Docker Compose on server
        env:
          DEBUG: ${{ vars.DEBUG }}
          ALLOWED_HOSTS: ${{ vars.ALLOWED_HOSTS }}
          CSRF_TRUSTED_ORIGINS: ${{ vars.CSRF_TRUSTED_ORIGINS }}
          FRONTEND_URL: ${{ vars.FRONTEND_URL }}
          PARENT_HOST: ${{ vars.PARENT_HOST }}
          EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        run: |
          ssh -p ${{ vars.PORT }} ${{ vars.USER }}@${{ vars.HOST }} "
          docker compose down &&
          docker compose build &&
          docker compose up -d
          "
