name: Django CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: PRODUCTION

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.PRODUCTION.SSH_KEY }}

      - name: Copy files to server
        run: |
          rsync -avz --exclude '.git/' --exclude '.github/' -e "ssh -p ${{ secrets.PRODUCTION.PORT }}" . ${{ secrets.PRODUCTION.USER }}@${{ secrets.PRODUCTION.HOST }}:/Portfolizer
      - name: Build Docker Compose on server
        env:
          DEBUG: ${{ secrets.PRODUCTION.DEBUG }}
          ALLOWED_HOSTS: ${{ secrets.PRODUCTION.ALLOWED_HOSTS }}
          CSRF_TRUSTED_ORIGINS: ${{ secrets.PRODUCTION.CSRF_TRUSTED_ORIGINS }}
          FRONTEND_URL: ${{ secrets.PRODUCTION.FRONTEND_URL }}
          PARENT_HOST: ${{ secrets.PRODUCTION.PARENT_HOST }}
          EMAIL_HOST_USER: ${{ secrets.PRODUCTION.EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD: ${{ secrets.PRODUCTION.EMAIL_HOST_PASSWORD }}
          DJANGO_SECRET_KEY: ${{ secrets.PRODUCTION.DJANGO_SECRET_KEY }}
        run: |
          ssh -p ${{ secrets.PRODUCTION.PORT }} ${{ secrets.PRODUCTION.USER }}@${{ secrets.PRODUCTION.HOST }} "
          docker compose down &&
          docker compose build &&
          docker compose up -d
          "
